cas:
  enable: false
  expiry: 28800 #8 hour
  url: https://cas.arrivu.corecloud.com
  login_path: '/cas/api-login'
  logout_path: '/cas/api-logout'  
lms:
  enable: false
  account_id: 1
  oauth_token: 3p36JvnjHXfp1d5NwTqmtKExNRFoowLeMwbtbXzJJz3hTPS4geis8YcA9XWYEcFn
  root_url: https://lms.arrivu.corecloud.com/
  course_url_path: /courses/
  api_root_url: https://lms.arrivu.corecloud.com/api/v1
  logout_path: logout
mailserver:
  address: smtp.gmail.com
  port: 587
  domain: "beacon-learning.herokuapp.com"
  user_name: beaconlms@gmail.com
  password: beaconlms123$
admin_mail:
  to: beaconlms@gmail.com
payment_gateway:
  enable: false 
  merchant_id: "M_blahpache_5678"
  work_key: "6abc0ty90e0v7jk9hj"
  ccavenue_account: "test123"
invoices:
  notes: "Thank you for your enrollment!"
exception_notifer:
  email_prefix: "[Beacon Exception Notifier]"
  sender_address: "beaconlms@gmail.com"
  exception_recipients: "beaconlms@gmail.com"
omniauth:
  facebook_key: "631186620244012"
  facebook_secret: "48339c2352a9579bcc7dc5ee215b1a7f"
  linkedin_key: "z1zu2sg48rvp"
  linkedin_secret: "8kpRB8V5EBsiXcbx"
  google_oauth2_key: "928801233183-phpisd2fada5c2d5n5heosha9h8jisla.apps.googleusercontent.com"
  google_oauth2_secret: "D6mLnz02jOX6kpT-cbo9p2MM"
